/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 회원가입 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description 회원가입 성공 (액세스/리프레시 토큰 쿠키 설정) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그인 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description 로그인 성공 (액세스/리프레시 토큰 쿠키 설정) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 액세스 토큰 갱신
         * @description 리프레시 토큰 쿠키를 사용하여 새 토큰 쌍을 발급한다.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 갱신 성공 (새 토큰 쿠키 설정) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그아웃 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 로그아웃 성공 (토큰 쿠키 만료 처리) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 현재 로그인된 사용자 정보 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 사용자 정보 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 커피 기록 목록 조회 */
        get: {
            parameters: {
                query?: {
                    /** @description 로그 타입 필터 */
                    log_type?: components["schemas"]["LogType"];
                    /** @description 시작 날짜 필터 (YYYY-MM-DD 또는 RFC3339) */
                    date_from?: string;
                    /** @description 종료 날짜 필터 (YYYY-MM-DD 또는 RFC3339) */
                    date_to?: string;
                    /** @description 페이지네이션 커서 (이전 응답의 next_cursor 값) */
                    cursor?: string;
                    /** @description 페이지당 항목 수 */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListLogsResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** 커피 기록 생성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateLogRequest"];
                };
            };
            responses: {
                /** @description 생성 성공 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CoffeeLogResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 커피 기록 단건 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 커피 기록 ID */
                    id: components["parameters"]["LogId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CoffeeLogResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        /** 커피 기록 수정 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 커피 기록 ID */
                    id: components["parameters"]["LogId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateLogRequest"];
                };
            };
            responses: {
                /** @description 수정 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CoffeeLogResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /** 커피 기록 삭제 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 커피 기록 ID */
                    id: components["parameters"]["LogId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 삭제 성공 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 프리셋 목록 조회 (최근 사용순) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListPresetsResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** 프리셋 생성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePresetRequest"];
                };
            };
            responses: {
                /** @description 생성 성공 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PresetResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 프리셋 단건 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 프리셋 ID */
                    id: components["parameters"]["PresetId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PresetResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        /** 프리셋 수정 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 프리셋 ID */
                    id: components["parameters"]["PresetId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdatePresetRequest"];
                };
            };
            responses: {
                /** @description 수정 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PresetResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /** 프리셋 삭제 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 프리셋 ID */
                    id: components["parameters"]["PresetId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 삭제 성공 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets/{id}/use": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 프리셋 사용 기록 (last_used_at 갱신) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 프리셋 ID */
                    id: components["parameters"]["PresetId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 사용 기록 성공 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suggestions/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 테이스팅 태그 자동완성 제안 */
        get: {
            parameters: {
                query?: {
                    /** @description 검색어 (빈 문자열이면 전체 반환) */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 제안 목록 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuggestionsResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suggestions/companions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 동반자 자동완성 제안 */
        get: {
            parameters: {
                query?: {
                    /** @description 검색어 (빈 문자열이면 전체 반환) */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 제안 목록 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuggestionsResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example mypassword123 */
            password: string;
            /** @example coffeelover */
            username: string;
            /**
             * @description 생략 시 username으로 대체
             * @example 커피러버
             */
            display_name?: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example mypassword123 */
            password: string;
        };
        UserResponse: {
            id: string;
            /** Format: email */
            email: string;
            username: string;
            display_name: string;
        };
        /**
         * @description cafe = 바리스타가 추출, brew = 내가 직접 추출
         * @enum {string}
         */
        LogType: "cafe" | "brew";
        /** @enum {string} */
        RoastLevel: "light" | "medium" | "dark";
        /** @enum {string} */
        BrewMethod: "pour_over" | "immersion" | "aeropress" | "espresso" | "moka_pot" | "siphon" | "cold_brew" | "other";
        CafeDetail: {
            /** @example 블루보틀 성수 */
            cafe_name: string;
            location?: string | null;
            /** @example 싱글 오리진 드립 */
            coffee_name: string;
            bean_origin?: string | null;
            bean_process?: string | null;
            /** @enum {string|null} */
            roast_level?: "light" | "medium" | "dark" | null;
            /**
             * @example [
             *       "초콜릿",
             *       "체리"
             *     ]
             */
            tasting_tags?: string[];
            tasting_note?: string | null;
            impressions?: string | null;
            rating?: number | null;
        };
        BrewDetail: {
            /** @example 에티오피아 예가체프 G1 */
            bean_name: string;
            bean_origin?: string | null;
            bean_process?: string | null;
            /** @enum {string|null} */
            roast_level?: "light" | "medium" | "dark" | null;
            /** Format: date */
            roast_date?: string | null;
            tasting_tags?: string[];
            tasting_note?: string | null;
            brew_method: components["schemas"]["BrewMethod"];
            /** @example Origami */
            brew_device?: string | null;
            coffee_amount_g?: number | null;
            water_amount_ml?: number | null;
            water_temp_c?: number | null;
            brew_time_sec?: number | null;
            grind_size?: string | null;
            brew_steps?: string[];
            impressions?: string | null;
            rating?: number | null;
        };
        CoffeeLogResponse: {
            id: string;
            user_id: string;
            /** Format: date-time */
            recorded_at: string;
            companions: string[];
            log_type: components["schemas"]["LogType"];
            memo?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            cafe?: components["schemas"]["CafeDetail"];
            brew?: components["schemas"]["BrewDetail"];
        };
        CreateLogRequest: {
            /**
             * @description RFC3339 datetime (예: 2026-03-29T10:00:00Z 또는 2026-03-29T10:00:00+09:00)
             * @example 2026-03-29T10:00:00Z
             */
            recorded_at: string;
            companions?: string[];
            log_type: components["schemas"]["LogType"];
            memo?: string | null;
            cafe?: components["schemas"]["CafeDetail"];
            brew?: components["schemas"]["BrewDetail"];
        };
        UpdateLogRequest: {
            /** @description RFC3339 datetime (예: 2026-03-29T10:00:00Z 또는 2026-03-29T10:00:00+09:00) */
            recorded_at: string;
            companions?: string[];
            log_type: components["schemas"]["LogType"];
            memo?: string | null;
            cafe?: components["schemas"]["CafeDetail"];
            brew?: components["schemas"]["BrewDetail"];
        };
        ListLogsResponse: {
            items: components["schemas"]["CoffeeLogResponse"][];
            /** @description 다음 페이지 커서 (has_next가 false이면 null) */
            next_cursor?: string | null;
            /** @description 다음 페이지 존재 여부 */
            has_next: boolean;
        };
        SuggestionsResponse: {
            /** @description 빈도순 정렬된 자동완성 제안 목록 */
            suggestions: string[];
        };
        CafePresetDetail: {
            /** @example 블루보틀 성수 */
            cafe_name: string;
            /** @example 싱글 오리진 */
            coffee_name: string;
            /**
             * @example [
             *       "초콜릿",
             *       "체리"
             *     ]
             */
            tasting_tags?: string[];
        };
        BrewPresetDetail: {
            /** @example 에티오피아 예가체프 */
            bean_name: string;
            brew_method: components["schemas"]["BrewMethod"];
            recipe_detail?: string | null;
            brew_steps?: string[];
        };
        PresetResponse: {
            id: string;
            user_id: string;
            /** @example ���근길 아메리카노 */
            name: string;
            log_type: components["schemas"]["LogType"];
            /** Format: date-time */
            last_used_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            cafe?: components["schemas"]["CafePresetDetail"];
            brew?: components["schemas"]["BrewPresetDetail"];
        };
        CreatePresetRequest: {
            /** @example 출근길 아메리카노 */
            name: string;
            log_type: components["schemas"]["LogType"];
            cafe?: components["schemas"]["CafePresetDetail"];
            brew?: components["schemas"]["BrewPresetDetail"];
        };
        UpdatePresetRequest: {
            name: string;
            cafe?: components["schemas"]["CafePresetDetail"];
            brew?: components["schemas"]["BrewPresetDetail"];
        };
        ListPresetsResponse: {
            items: components["schemas"]["PresetResponse"][];
        };
        ErrorResponse: {
            /** @example 이메일 또는 비밀번호가 올바르지 않습니다 */
            error?: string;
            /**
             * @description ValidationError일 때만 포함. 오류가 발생한 필드 경로 (예: email)
             * @example email
             */
            field?: string;
        };
    };
    responses: {
        /** @description 잘못된 요청 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 인증 실패 (토큰 없음 또는 만료) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 기록을 찾을 수 없거나 다른 사용자 소유 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 이미 사용 중인 이메일 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description 커피 기록 ID */
        LogId: string;
        /** @description 프리셋 ID */
        PresetId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
