/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 커피 기록 목록 조회 */
        get: {
            parameters: {
                query?: {
                    /** @description 로그 타입 필터 */
                    log_type?: components["schemas"]["LogType"];
                    /** @description 시작 날짜 필터 (YYYY-MM-DD 또는 RFC3339) */
                    date_from?: string;
                    /** @description 종료 날짜 필터 (YYYY-MM-DD 또는 RFC3339) */
                    date_to?: string;
                    /** @description 페이지네이션 커서 (이전 응답의 next_cursor 값) */
                    cursor?: string;
                    /** @description 페이지당 항목 수 */
                    limit?: number;
                };
                header: {
                    /** @description 사용자 식별자 (POC 단계; Phase 4에서 JWT로 교체) */
                    "X-User-Id": components["parameters"]["XUserId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListLogsResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** 커피 기록 생성 */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 사용자 식별자 (POC 단계; Phase 4에서 JWT로 교체) */
                    "X-User-Id": components["parameters"]["XUserId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateLogRequest"];
                };
            };
            responses: {
                /** @description 생성 성공 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CoffeeLogResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 커피 기록 단건 조회 */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description 사용자 식별자 (POC 단계; Phase 4에서 JWT로 교체) */
                    "X-User-Id": components["parameters"]["XUserId"];
                };
                path: {
                    /** @description 커피 기록 ID */
                    id: components["parameters"]["LogId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CoffeeLogResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        /** 커피 기록 수정 */
        put: {
            parameters: {
                query?: never;
                header: {
                    /** @description 사용자 식별자 (POC 단계; Phase 4에서 JWT로 교체) */
                    "X-User-Id": components["parameters"]["XUserId"];
                };
                path: {
                    /** @description 커피 기록 ID */
                    id: components["parameters"]["LogId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateLogRequest"];
                };
            };
            responses: {
                /** @description 수정 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CoffeeLogResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /** 커피 기록 삭제 */
        delete: {
            parameters: {
                query?: never;
                header: {
                    /** @description 사용자 식별자 (POC 단계; Phase 4에서 JWT로 교체) */
                    "X-User-Id": components["parameters"]["XUserId"];
                };
                path: {
                    /** @description 커피 기록 ID */
                    id: components["parameters"]["LogId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 삭제 성공 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description cafe = 바리스타가 추출, brew = 내가 직접 추출
         * @enum {string}
         */
        LogType: "cafe" | "brew";
        /** @enum {string} */
        RoastLevel: "light" | "medium" | "dark";
        /** @enum {string} */
        BrewMethod: "pour_over" | "immersion" | "aeropress" | "espresso" | "moka_pot" | "siphon" | "cold_brew" | "other";
        CafeDetail: {
            /** @example 블루보틀 성수 */
            cafe_name: string;
            location?: string | null;
            /** @example 싱글 오리진 드립 */
            coffee_name: string;
            bean_origin?: string | null;
            bean_process?: string | null;
            /** @enum {string|null} */
            roast_level?: "light" | "medium" | "dark" | null;
            /**
             * @example [
             *       "초콜릿",
             *       "체리"
             *     ]
             */
            tasting_tags?: string[];
            tasting_note?: string | null;
            impressions?: string | null;
            rating?: number | null;
        };
        BrewDetail: {
            /** @example 에티오피아 예가체프 G1 */
            bean_name: string;
            bean_origin?: string | null;
            bean_process?: string | null;
            /** @enum {string|null} */
            roast_level?: "light" | "medium" | "dark" | null;
            /** Format: date */
            roast_date?: string | null;
            tasting_tags?: string[];
            tasting_note?: string | null;
            brew_method: components["schemas"]["BrewMethod"];
            /** @example Origami */
            brew_device?: string | null;
            coffee_amount_g?: number | null;
            water_amount_ml?: number | null;
            water_temp_c?: number | null;
            brew_time_sec?: number | null;
            grind_size?: string | null;
            brew_steps?: string[];
            impressions?: string | null;
            rating?: number | null;
        };
        CoffeeLogResponse: {
            id: string;
            user_id: string;
            /** Format: date-time */
            recorded_at: string;
            companions: string[];
            log_type: components["schemas"]["LogType"];
            memo?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            cafe?: components["schemas"]["CafeDetail"];
            brew?: components["schemas"]["BrewDetail"];
        };
        CreateLogRequest: {
            /**
             * @description RFC3339 또는 YYYY-MM-DD
             * @example 2026-03-29T10:00:00Z
             */
            recorded_at: string;
            companions?: string[];
            log_type: components["schemas"]["LogType"];
            memo?: string | null;
            cafe?: components["schemas"]["CafeDetail"];
            brew?: components["schemas"]["BrewDetail"];
        };
        UpdateLogRequest: {
            /** @description RFC3339 또는 YYYY-MM-DD */
            recorded_at: string;
            companions?: string[];
            log_type: components["schemas"]["LogType"];
            memo?: string | null;
            cafe?: components["schemas"]["CafeDetail"];
            brew?: components["schemas"]["BrewDetail"];
        };
        ListLogsResponse: {
            items: components["schemas"]["CoffeeLogResponse"][];
            /** @description 다음 페이지 커서 (has_next가 false이면 null) */
            next_cursor?: string | null;
            /** @description 다음 페이지 존재 여부 */
            has_next: boolean;
        };
        ErrorResponse: {
            /** @example X-User-Id 헤더가 필요합니다 */
            error?: string;
        };
    };
    responses: {
        /** @description 잘못된 요청 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description X-User-Id 헤더 누락 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 기록을 찾을 수 없거나 다른 사용자 소유 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description 사용자 식별자 (POC 단계; Phase 4에서 JWT로 교체) */
        XUserId: string;
        /** @description 커피 기록 ID */
        LogId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
