// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: brew_presets.sql

package db

import (
	"context"
)

const getBrewPresetByPresetID = `-- name: GetBrewPresetByPresetID :one
SELECT preset_id, bean_name, brew_method, recipe_detail, brew_steps
FROM brew_presets
WHERE preset_id = ?
`

func (q *Queries) GetBrewPresetByPresetID(ctx context.Context, presetID string) (BrewPreset, error) {
	row := q.db.QueryRowContext(ctx, getBrewPresetByPresetID, presetID)
	var i BrewPreset
	err := row.Scan(
		&i.PresetID,
		&i.BeanName,
		&i.BrewMethod,
		&i.RecipeDetail,
		&i.BrewSteps,
	)
	return i, err
}

const insertBrewPreset = `-- name: InsertBrewPreset :exec
INSERT INTO brew_presets (preset_id, bean_name, brew_method, recipe_detail, brew_steps)
VALUES (?, ?, ?, ?, ?)
`

type InsertBrewPresetParams struct {
	PresetID     string  `json:"preset_id"`
	BeanName     string  `json:"bean_name"`
	BrewMethod   string  `json:"brew_method"`
	RecipeDetail *string `json:"recipe_detail"`
	BrewSteps    string  `json:"brew_steps"`
}

func (q *Queries) InsertBrewPreset(ctx context.Context, arg InsertBrewPresetParams) error {
	_, err := q.db.ExecContext(ctx, insertBrewPreset,
		arg.PresetID,
		arg.BeanName,
		arg.BrewMethod,
		arg.RecipeDetail,
		arg.BrewSteps,
	)
	return err
}

const updateBrewPreset = `-- name: UpdateBrewPreset :exec
UPDATE brew_presets
SET bean_name = ?, brew_method = ?, recipe_detail = ?, brew_steps = ?
WHERE preset_id = ?
`

type UpdateBrewPresetParams struct {
	BeanName     string  `json:"bean_name"`
	BrewMethod   string  `json:"brew_method"`
	RecipeDetail *string `json:"recipe_detail"`
	BrewSteps    string  `json:"brew_steps"`
	PresetID     string  `json:"preset_id"`
}

func (q *Queries) UpdateBrewPreset(ctx context.Context, arg UpdateBrewPresetParams) error {
	_, err := q.db.ExecContext(ctx, updateBrewPreset,
		arg.BeanName,
		arg.BrewMethod,
		arg.RecipeDetail,
		arg.BrewSteps,
		arg.PresetID,
	)
	return err
}
