// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: brew_logs.sql

package db

import (
	"context"
)

const getBrewLogByLogID = `-- name: GetBrewLogByLogID :one
SELECT log_id, bean_name, bean_origin, bean_process, roast_level, roast_date, tasting_tags, tasting_note, brew_method, brew_device, coffee_amount_g, water_amount_ml, water_temp_c, brew_time_sec, grind_size, brew_steps, impressions, rating
FROM brew_logs
WHERE log_id = ?
`

func (q *Queries) GetBrewLogByLogID(ctx context.Context, logID string) (BrewLog, error) {
	row := q.db.QueryRowContext(ctx, getBrewLogByLogID, logID)
	var i BrewLog
	err := row.Scan(
		&i.LogID,
		&i.BeanName,
		&i.BeanOrigin,
		&i.BeanProcess,
		&i.RoastLevel,
		&i.RoastDate,
		&i.TastingTags,
		&i.TastingNote,
		&i.BrewMethod,
		&i.BrewDevice,
		&i.CoffeeAmountG,
		&i.WaterAmountMl,
		&i.WaterTempC,
		&i.BrewTimeSec,
		&i.GrindSize,
		&i.BrewSteps,
		&i.Impressions,
		&i.Rating,
	)
	return i, err
}

const insertBrewLog = `-- name: InsertBrewLog :exec
INSERT INTO brew_logs (log_id, bean_name, bean_origin, bean_process, roast_level, roast_date, tasting_tags, tasting_note, brew_method, brew_device, coffee_amount_g, water_amount_ml, water_temp_c, brew_time_sec, grind_size, brew_steps, impressions, rating)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertBrewLogParams struct {
	LogID         string   `json:"log_id"`
	BeanName      string   `json:"bean_name"`
	BeanOrigin    *string  `json:"bean_origin"`
	BeanProcess   *string  `json:"bean_process"`
	RoastLevel    *string  `json:"roast_level"`
	RoastDate     *string  `json:"roast_date"`
	TastingTags   string   `json:"tasting_tags"`
	TastingNote   *string  `json:"tasting_note"`
	BrewMethod    string   `json:"brew_method"`
	BrewDevice    *string  `json:"brew_device"`
	CoffeeAmountG *float64 `json:"coffee_amount_g"`
	WaterAmountMl *float64 `json:"water_amount_ml"`
	WaterTempC    *float64 `json:"water_temp_c"`
	BrewTimeSec   *int64   `json:"brew_time_sec"`
	GrindSize     *string  `json:"grind_size"`
	BrewSteps     string   `json:"brew_steps"`
	Impressions   *string  `json:"impressions"`
	Rating        *float64 `json:"rating"`
}

func (q *Queries) InsertBrewLog(ctx context.Context, arg InsertBrewLogParams) error {
	_, err := q.db.ExecContext(ctx, insertBrewLog,
		arg.LogID,
		arg.BeanName,
		arg.BeanOrigin,
		arg.BeanProcess,
		arg.RoastLevel,
		arg.RoastDate,
		arg.TastingTags,
		arg.TastingNote,
		arg.BrewMethod,
		arg.BrewDevice,
		arg.CoffeeAmountG,
		arg.WaterAmountMl,
		arg.WaterTempC,
		arg.BrewTimeSec,
		arg.GrindSize,
		arg.BrewSteps,
		arg.Impressions,
		arg.Rating,
	)
	return err
}

const updateBrewLog = `-- name: UpdateBrewLog :exec
UPDATE brew_logs
SET bean_name = ?, bean_origin = ?, bean_process = ?, roast_level = ?, roast_date = ?, tasting_tags = ?, tasting_note = ?, brew_method = ?, brew_device = ?, coffee_amount_g = ?, water_amount_ml = ?, water_temp_c = ?, brew_time_sec = ?, grind_size = ?, brew_steps = ?, impressions = ?, rating = ?
WHERE log_id = ?
`

type UpdateBrewLogParams struct {
	BeanName      string   `json:"bean_name"`
	BeanOrigin    *string  `json:"bean_origin"`
	BeanProcess   *string  `json:"bean_process"`
	RoastLevel    *string  `json:"roast_level"`
	RoastDate     *string  `json:"roast_date"`
	TastingTags   string   `json:"tasting_tags"`
	TastingNote   *string  `json:"tasting_note"`
	BrewMethod    string   `json:"brew_method"`
	BrewDevice    *string  `json:"brew_device"`
	CoffeeAmountG *float64 `json:"coffee_amount_g"`
	WaterAmountMl *float64 `json:"water_amount_ml"`
	WaterTempC    *float64 `json:"water_temp_c"`
	BrewTimeSec   *int64   `json:"brew_time_sec"`
	GrindSize     *string  `json:"grind_size"`
	BrewSteps     string   `json:"brew_steps"`
	Impressions   *string  `json:"impressions"`
	Rating        *float64 `json:"rating"`
	LogID         string   `json:"log_id"`
}

func (q *Queries) UpdateBrewLog(ctx context.Context, arg UpdateBrewLogParams) error {
	_, err := q.db.ExecContext(ctx, updateBrewLog,
		arg.BeanName,
		arg.BeanOrigin,
		arg.BeanProcess,
		arg.RoastLevel,
		arg.RoastDate,
		arg.TastingTags,
		arg.TastingNote,
		arg.BrewMethod,
		arg.BrewDevice,
		arg.CoffeeAmountG,
		arg.WaterAmountMl,
		arg.WaterTempC,
		arg.BrewTimeSec,
		arg.GrindSize,
		arg.BrewSteps,
		arg.Impressions,
		arg.Rating,
		arg.LogID,
	)
	return err
}
