// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cafe_logs.sql

package db

import (
	"context"
)

const getCafeLogByLogID = `-- name: GetCafeLogByLogID :one
SELECT log_id, cafe_name, location, coffee_name, bean_origin, bean_process, roast_level, tasting_tags, tasting_note, impressions, rating
FROM cafe_logs
WHERE log_id = ?
`

func (q *Queries) GetCafeLogByLogID(ctx context.Context, logID string) (CafeLog, error) {
	row := q.db.QueryRowContext(ctx, getCafeLogByLogID, logID)
	var i CafeLog
	err := row.Scan(
		&i.LogID,
		&i.CafeName,
		&i.Location,
		&i.CoffeeName,
		&i.BeanOrigin,
		&i.BeanProcess,
		&i.RoastLevel,
		&i.TastingTags,
		&i.TastingNote,
		&i.Impressions,
		&i.Rating,
	)
	return i, err
}

const insertCafeLog = `-- name: InsertCafeLog :exec
INSERT INTO cafe_logs (log_id, cafe_name, location, coffee_name, bean_origin, bean_process, roast_level, tasting_tags, tasting_note, impressions, rating)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertCafeLogParams struct {
	LogID       string   `json:"log_id"`
	CafeName    string   `json:"cafe_name"`
	Location    *string  `json:"location"`
	CoffeeName  string   `json:"coffee_name"`
	BeanOrigin  *string  `json:"bean_origin"`
	BeanProcess *string  `json:"bean_process"`
	RoastLevel  *string  `json:"roast_level"`
	TastingTags string   `json:"tasting_tags"`
	TastingNote *string  `json:"tasting_note"`
	Impressions *string  `json:"impressions"`
	Rating      *float64 `json:"rating"`
}

func (q *Queries) InsertCafeLog(ctx context.Context, arg InsertCafeLogParams) error {
	_, err := q.db.ExecContext(ctx, insertCafeLog,
		arg.LogID,
		arg.CafeName,
		arg.Location,
		arg.CoffeeName,
		arg.BeanOrigin,
		arg.BeanProcess,
		arg.RoastLevel,
		arg.TastingTags,
		arg.TastingNote,
		arg.Impressions,
		arg.Rating,
	)
	return err
}

const updateCafeLog = `-- name: UpdateCafeLog :exec
UPDATE cafe_logs
SET cafe_name = ?, location = ?, coffee_name = ?, bean_origin = ?, bean_process = ?, roast_level = ?, tasting_tags = ?, tasting_note = ?, impressions = ?, rating = ?
WHERE log_id = ?
`

type UpdateCafeLogParams struct {
	CafeName    string   `json:"cafe_name"`
	Location    *string  `json:"location"`
	CoffeeName  string   `json:"coffee_name"`
	BeanOrigin  *string  `json:"bean_origin"`
	BeanProcess *string  `json:"bean_process"`
	RoastLevel  *string  `json:"roast_level"`
	TastingTags string   `json:"tasting_tags"`
	TastingNote *string  `json:"tasting_note"`
	Impressions *string  `json:"impressions"`
	Rating      *float64 `json:"rating"`
	LogID       string   `json:"log_id"`
}

func (q *Queries) UpdateCafeLog(ctx context.Context, arg UpdateCafeLogParams) error {
	_, err := q.db.ExecContext(ctx, updateCafeLog,
		arg.CafeName,
		arg.Location,
		arg.CoffeeName,
		arg.BeanOrigin,
		arg.BeanProcess,
		arg.RoastLevel,
		arg.TastingTags,
		arg.TastingNote,
		arg.Impressions,
		arg.Rating,
		arg.LogID,
	)
	return err
}
