// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cafe_presets.sql

package db

import (
	"context"
)

const getCafePresetByPresetID = `-- name: GetCafePresetByPresetID :one
SELECT preset_id, cafe_name, coffee_name, tasting_tags
FROM cafe_presets
WHERE preset_id = ?
`

func (q *Queries) GetCafePresetByPresetID(ctx context.Context, presetID string) (CafePreset, error) {
	row := q.db.QueryRowContext(ctx, getCafePresetByPresetID, presetID)
	var i CafePreset
	err := row.Scan(
		&i.PresetID,
		&i.CafeName,
		&i.CoffeeName,
		&i.TastingTags,
	)
	return i, err
}

const insertCafePreset = `-- name: InsertCafePreset :exec
INSERT INTO cafe_presets (preset_id, cafe_name, coffee_name, tasting_tags)
VALUES (?, ?, ?, ?)
`

type InsertCafePresetParams struct {
	PresetID    string `json:"preset_id"`
	CafeName    string `json:"cafe_name"`
	CoffeeName  string `json:"coffee_name"`
	TastingTags string `json:"tasting_tags"`
}

func (q *Queries) InsertCafePreset(ctx context.Context, arg InsertCafePresetParams) error {
	_, err := q.db.ExecContext(ctx, insertCafePreset,
		arg.PresetID,
		arg.CafeName,
		arg.CoffeeName,
		arg.TastingTags,
	)
	return err
}

const updateCafePreset = `-- name: UpdateCafePreset :exec
UPDATE cafe_presets
SET cafe_name = ?, coffee_name = ?, tasting_tags = ?
WHERE preset_id = ?
`

type UpdateCafePresetParams struct {
	CafeName    string `json:"cafe_name"`
	CoffeeName  string `json:"coffee_name"`
	TastingTags string `json:"tasting_tags"`
	PresetID    string `json:"preset_id"`
}

func (q *Queries) UpdateCafePreset(ctx context.Context, arg UpdateCafePresetParams) error {
	_, err := q.db.ExecContext(ctx, updateCafePreset,
		arg.CafeName,
		arg.CoffeeName,
		arg.TastingTags,
		arg.PresetID,
	)
	return err
}
