// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coffee_logs.sql

package db

import (
	"context"
)

const deleteLog = `-- name: DeleteLog :exec
DELETE FROM coffee_logs
WHERE id = ? AND user_id = ?
`

type DeleteLogParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteLog(ctx context.Context, arg DeleteLogParams) error {
	_, err := q.db.ExecContext(ctx, deleteLog, arg.ID, arg.UserID)
	return err
}

const getLogByID = `-- name: GetLogByID :one
SELECT id, user_id, recorded_at, companions, log_type, memo, created_at, updated_at
FROM coffee_logs
WHERE id = ? AND user_id = ?
`

type GetLogByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetLogByID(ctx context.Context, arg GetLogByIDParams) (CoffeeLog, error) {
	row := q.db.QueryRowContext(ctx, getLogByID, arg.ID, arg.UserID)
	var i CoffeeLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecordedAt,
		&i.Companions,
		&i.LogType,
		&i.Memo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLog = `-- name: InsertLog :exec
INSERT INTO coffee_logs (id, user_id, recorded_at, companions, log_type, memo, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertLogParams struct {
	ID         string  `json:"id"`
	UserID     string  `json:"user_id"`
	RecordedAt string  `json:"recorded_at"`
	Companions string  `json:"companions"`
	LogType    string  `json:"log_type"`
	Memo       *string `json:"memo"`
	CreatedAt  string  `json:"created_at"`
	UpdatedAt  string  `json:"updated_at"`
}

func (q *Queries) InsertLog(ctx context.Context, arg InsertLogParams) error {
	_, err := q.db.ExecContext(ctx, insertLog,
		arg.ID,
		arg.UserID,
		arg.RecordedAt,
		arg.Companions,
		arg.LogType,
		arg.Memo,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listLogs = `-- name: ListLogs :many
SELECT id, user_id, recorded_at, companions, log_type, memo, created_at, updated_at
FROM coffee_logs
WHERE user_id = ?
  AND (?3 IS NULL OR log_type = ?3)
  AND (?4 IS NULL OR recorded_at >= ?4)
  AND (?5 IS NULL OR recorded_at <= ?5)
  AND (
    ?6 IS NULL
    OR recorded_at < ?6
    OR (recorded_at = ?6 AND id < ?7)
  )
ORDER BY recorded_at DESC, id DESC
LIMIT ?
`

type ListLogsParams struct {
	UserID           string      `json:"user_id"`
	LogType          interface{} `json:"log_type"`
	DateFrom         interface{} `json:"date_from"`
	DateTo           interface{} `json:"date_to"`
	CursorRecordedAt interface{} `json:"cursor_recorded_at"`
	CursorID         *string     `json:"cursor_id"`
	Limit            int64       `json:"limit"`
}

func (q *Queries) ListLogs(ctx context.Context, arg ListLogsParams) ([]CoffeeLog, error) {
	rows, err := q.db.QueryContext(ctx, listLogs,
		arg.UserID,
		arg.LogType,
		arg.DateFrom,
		arg.DateTo,
		arg.CursorRecordedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoffeeLog
	for rows.Next() {
		var i CoffeeLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RecordedAt,
			&i.Companions,
			&i.LogType,
			&i.Memo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLog = `-- name: UpdateLog :exec
UPDATE coffee_logs
SET recorded_at = ?, companions = ?, memo = ?, updated_at = ?
WHERE id = ? AND user_id = ?
`

type UpdateLogParams struct {
	RecordedAt string  `json:"recorded_at"`
	Companions string  `json:"companions"`
	Memo       *string `json:"memo"`
	UpdatedAt  string  `json:"updated_at"`
	ID         string  `json:"id"`
	UserID     string  `json:"user_id"`
}

func (q *Queries) UpdateLog(ctx context.Context, arg UpdateLogParams) error {
	_, err := q.db.ExecContext(ctx, updateLog,
		arg.RecordedAt,
		arg.Companions,
		arg.Memo,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}
