// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type BrewLog struct {
	LogID         string   `json:"log_id"`
	BeanName      string   `json:"bean_name"`
	BeanOrigin    *string  `json:"bean_origin"`
	BeanProcess   *string  `json:"bean_process"`
	RoastLevel    *string  `json:"roast_level"`
	RoastDate     *string  `json:"roast_date"`
	TastingTags   string   `json:"tasting_tags"`
	TastingNote   *string  `json:"tasting_note"`
	BrewMethod    string   `json:"brew_method"`
	BrewDevice    *string  `json:"brew_device"`
	CoffeeAmountG *float64 `json:"coffee_amount_g"`
	WaterAmountMl *float64 `json:"water_amount_ml"`
	WaterTempC    *float64 `json:"water_temp_c"`
	BrewTimeSec   *int64   `json:"brew_time_sec"`
	GrindSize     *string  `json:"grind_size"`
	BrewSteps     string   `json:"brew_steps"`
	Impressions   *string  `json:"impressions"`
	Rating        *float64 `json:"rating"`
}

type CafeLog struct {
	LogID       string   `json:"log_id"`
	CafeName    string   `json:"cafe_name"`
	Location    *string  `json:"location"`
	CoffeeName  string   `json:"coffee_name"`
	BeanOrigin  *string  `json:"bean_origin"`
	BeanProcess *string  `json:"bean_process"`
	RoastLevel  *string  `json:"roast_level"`
	TastingTags string   `json:"tasting_tags"`
	TastingNote *string  `json:"tasting_note"`
	Impressions *string  `json:"impressions"`
	Rating      *float64 `json:"rating"`
}

type CoffeeLog struct {
	ID         string  `json:"id"`
	UserID     string  `json:"user_id"`
	RecordedAt string  `json:"recorded_at"`
	Companions string  `json:"companions"`
	LogType    string  `json:"log_type"`
	Memo       *string `json:"memo"`
	CreatedAt  string  `json:"created_at"`
	UpdatedAt  string  `json:"updated_at"`
}

type User struct {
	ID           string  `json:"id"`
	Username     string  `json:"username"`
	DisplayName  string  `json:"display_name"`
	CreatedAt    string  `json:"created_at"`
	Email        *string `json:"email"`
	PasswordHash *string `json:"password_hash"`
	TokenVersion int64   `json:"token_version"`
}
