// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: presets.sql

package db

import (
	"context"
)

const deletePreset = `-- name: DeletePreset :exec
DELETE FROM presets
WHERE id = ? AND user_id = ?
`

type DeletePresetParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeletePreset(ctx context.Context, arg DeletePresetParams) error {
	_, err := q.db.ExecContext(ctx, deletePreset, arg.ID, arg.UserID)
	return err
}

const getPresetByID = `-- name: GetPresetByID :one
SELECT id, user_id, name, log_type, last_used_at, created_at, updated_at
FROM presets
WHERE id = ? AND user_id = ?
`

type GetPresetByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetPresetByID(ctx context.Context, arg GetPresetByIDParams) (Preset, error) {
	row := q.db.QueryRowContext(ctx, getPresetByID, arg.ID, arg.UserID)
	var i Preset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.LogType,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPreset = `-- name: InsertPreset :exec
INSERT INTO presets (id, user_id, name, log_type, last_used_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertPresetParams struct {
	ID         string  `json:"id"`
	UserID     string  `json:"user_id"`
	Name       string  `json:"name"`
	LogType    string  `json:"log_type"`
	LastUsedAt *string `json:"last_used_at"`
	CreatedAt  string  `json:"created_at"`
	UpdatedAt  string  `json:"updated_at"`
}

func (q *Queries) InsertPreset(ctx context.Context, arg InsertPresetParams) error {
	_, err := q.db.ExecContext(ctx, insertPreset,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.LogType,
		arg.LastUsedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listPresetsByUserID = `-- name: ListPresetsByUserID :many
SELECT id, user_id, name, log_type, last_used_at, created_at, updated_at
FROM presets
WHERE user_id = ?
ORDER BY CASE WHEN last_used_at IS NULL THEN 1 ELSE 0 END, last_used_at DESC, created_at DESC
`

func (q *Queries) ListPresetsByUserID(ctx context.Context, userID string) ([]Preset, error) {
	rows, err := q.db.QueryContext(ctx, listPresetsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Preset
	for rows.Next() {
		var i Preset
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.LogType,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePreset = `-- name: UpdatePreset :exec
UPDATE presets
SET name = ?, updated_at = ?
WHERE id = ? AND user_id = ?
`

type UpdatePresetParams struct {
	Name      string `json:"name"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) UpdatePreset(ctx context.Context, arg UpdatePresetParams) error {
	_, err := q.db.ExecContext(ctx, updatePreset,
		arg.Name,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updatePresetLastUsedAt = `-- name: UpdatePresetLastUsedAt :exec
UPDATE presets
SET last_used_at = ?, updated_at = ?
WHERE id = ? AND user_id = ?
`

type UpdatePresetLastUsedAtParams struct {
	LastUsedAt *string `json:"last_used_at"`
	UpdatedAt  string  `json:"updated_at"`
	ID         string  `json:"id"`
	UserID     string  `json:"user_id"`
}

func (q *Queries) UpdatePresetLastUsedAt(ctx context.Context, arg UpdatePresetLastUsedAtParams) error {
	_, err := q.db.ExecContext(ctx, updatePresetLastUsedAt,
		arg.LastUsedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}
