// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, display_name, email, password_hash, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, username, display_name, created_at, email, password_hash, token_version
`

type CreateUserParams struct {
	ID           string  `json:"id"`
	Username     string  `json:"username"`
	DisplayName  string  `json:"display_name"`
	Email        *string `json:"email"`
	PasswordHash *string `json:"password_hash"`
	CreatedAt    string  `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.CreatedAt,
		&i.Email,
		&i.PasswordHash,
		&i.TokenVersion,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, display_name, created_at, email, password_hash, token_version FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.CreatedAt,
		&i.Email,
		&i.PasswordHash,
		&i.TokenVersion,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, display_name, created_at, email, password_hash, token_version FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.CreatedAt,
		&i.Email,
		&i.PasswordHash,
		&i.TokenVersion,
	)
	return i, err
}

const incrementTokenVersion = `-- name: IncrementTokenVersion :exec
UPDATE users SET token_version = token_version + 1 WHERE id = ?
`

func (q *Queries) IncrementTokenVersion(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementTokenVersion, id)
	return err
}
